version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:Qwerty12@postgres-server-container:5432/tasks-db?schema=public
      - JWT_SECRET=ashdfjhasdlkjfhalksdjhflak
    networks:
      - app-network
    volumes: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge